PREFIX drugbank: <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/>
PREFIX linkedCT: <http://data.linkedct.org/resource/linkedct/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT DISTINCT *
WHERE{
    ?intervention a linkedCT:intervention;
    linkedCT:intervention_name ?intervention_name;
    linkedCT:intervention_type ?intervention_type;
    rdfs:seeAlso ?drugbankDrug.
    ?drugbankDrug drugbank:structure ?structure;
    drugbank:state ?state;
    drugbank:proteinBinding ?proteinBinding;
    drugbank:smilesStringCanonical ?smilesStringCanonical.
}