PREFIX drugbank: <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/>
PREFIX tcga: <http://tcga.deri.ie/schema/>
PREFIX kegg: <http://bio2rdf.org/ns/kegg#>
PREFIX purl: <http://purl.org/dc/elements/1.1/>
SELECT *
WHERE {
    ?uri tcga:bcr_patient_barcode ?patient .
    ?patient tcga:gender ?gender.
    ?patient tcga:bcr_drug_barcode ?drugbcr.
    ?drugbcr tcga:drug_name ?drugName.
    ?drgBnkDrg drugbank:genericName ?drugName.
    ?drgBnkDrg drugbank:indication ?indication.
    ?drgBnkDrg drugbank:chemicalFormula ?chemicalFormula.
    ?drgBnkDrg drugbank:keggCompoundId ?compound.
}